# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xme_about_widget/QWAboutXMeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QWAboutXMeWidget(object):
    def setupUi(self, QWAboutXMeWidget):
        QWAboutXMeWidget.setObjectName("QWAboutXMeWidget")
        QWAboutXMeWidget.resize(647, 399)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        QWAboutXMeWidget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/images/pilab_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QWAboutXMeWidget.setWindowIcon(icon)
        self.lbl_Logo = QtWidgets.QLabel(QWAboutXMeWidget)
        self.lbl_Logo.setGeometry(QtCore.QRect(10, 10, 200, 137))
        self.lbl_Logo.setObjectName("lbl_Logo")
        self.lbl_Title = QtWidgets.QLabel(QWAboutXMeWidget)
        self.lbl_Title.setGeometry(QtCore.QRect(230, 10, 341, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Title.setFont(font)
        self.lbl_Title.setObjectName("lbl_Title")
        self.lbl_Main = QtWidgets.QLabel(QWAboutXMeWidget)
        self.lbl_Main.setGeometry(QtCore.QRect(230, 80, 401, 111))
        self.lbl_Main.setObjectName("lbl_Main")
        self.textBrowser = QtWidgets.QTextBrowser(QWAboutXMeWidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 200, 401, 161))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(QWAboutXMeWidget)
        self.label.setGeometry(QtCore.QRect(420, 370, 211, 21))
        self.label.setObjectName("label")

        self.retranslateUi(QWAboutXMeWidget)
        QtCore.QMetaObject.connectSlotsByName(QWAboutXMeWidget)

    def retranslateUi(self, QWAboutXMeWidget):
        _translate = QtCore.QCoreApplication.translate
        QWAboutXMeWidget.setWindowTitle(_translate("QWAboutXMeWidget", "About"))
        self.lbl_Logo.setText(_translate("QWAboutXMeWidget", "<html><head/><body><p><img src=\":/png/images/pilab-logo_new.png\"/></p></body></html>"))
        self.lbl_Title.setText(_translate("QWAboutXMeWidget", "<html><head/><body><p>XMe-DataAnalysis {version}</p></body></html>"))
        self.lbl_Main.setText(_translate("QWAboutXMeWidget", "<html><head/><body><p><span style=\" font-size:10pt;\">Based on Python(3.9+) and Pyqt5, licensed under the Apache2.0</span></p><p><span style=\" font-size:10pt;\">Built on Oct 30 2021</span></p><p><span style=\" font-size:10pt;\">Copyright © 2019-2021 Pilab Xiamen University</span></p><p><span style=\" font-size:10pt;\">Use need reference</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("QWAboutXMeWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Party A will state “The single-molecule conductance measurements are carried out using Xtech STMBJ developed by Prof. Wenjing Hong’s group in Xiamen University, and the data is analyzed by XMe open-source code.” in the section of experimental method in the papers from the instrument, and cite 3 references in the paper as follows:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">1. Liu, J.; …Hong, W., Transition from tunneling leakage current to molecular tunneling in single-molecule junctions, Chem, 2019, 5, 390-401.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">2. Bai, J.; … Hong, W., Anti-resonance features of destructive quantum interference in single-molecule thiophene junctions achieved by electrochemical gating, Nature Materials, 2019, 18, 364–369.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">3. Tang, C.; …Hong, W., Multicenter-Bond-Based quantum interference in charge transport through single-molecule carborane junctions, Angewandte Chemie International Editions, 2019, 58 (31), 10601-10605.</span></p></body></html>"))
        self.label.setText(_translate("QWAboutXMeWidget", "<html><head/><body><p>Support: <a href=\"mailto:GangDong@outlook.com\"><span style=\" text-decoration: underline; color:#0000ff;\">GangDong@outlook.com</span></a></p></body></html>"))
import images_rc
